### ISSUE TITLE
CPFValidationBehavior throws NullReferenceException when cpf parameter is null

### ISSUE THREAD

**Issue by guiportooo** [TBertuzzi/Xamarin.Forms.BehaviorValidationPack#1]
Hi,

First, thank you so much for this awesome plugin :)

## Expected Behavior
I'm using the **CPFValidationBehavior** in conjunction with the **XfxEntry** from [Xamarin Forms Extended Controls](https://github.com/XamFormsExtended/Xfx.Controls).
In this scenario, if the behavior validation is triggered when the entry is empty, the method **CpfValidator** should not throw a **NullReferenceException**.

## Actual Behavior
When the **CPFValidationBehavior** is applied to a **XfxEntry**, if the validation is triggered when the entry is empty (For example, when unfocusing the entry), a **NullReferenceException** is thrown by the method **CpfValidator**, because **xfxEntry** is sending the **cpf** value as **null**.

## Steps to Reproduce the Problem

  1. Add a **XfxEntry** with the **CPFValidationBehavior** to the page
  2. Click on the entry but don't type any value
  3. Unfocus the **XfxEntry**
  4. A **NullReferenceException** is thrown by the **CpfValidator** method

## Code example
```xml
<xfx:XfxEntry Placeholder="CPF" Keyboard="Numeric">
    <xfx:XfxEntry.Behaviors>
        <behaviorValidation:MaskedBehavior Mask="XXX.XXX.XXX-XX" />
        <behaviorValidation:CPFValidationBehavior />
    </xfx:XfxEntry.Behaviors>
</xfx:XfxEntry>
```

## Specifications

  - Xamarin.Forms.BehaviorValidationPack Version: 1.0.1
  - Xfx.Controls Version: 1.1.3
  - Platform: XamarinForms 3.3.0.912549

**Comment by guiportooo** [comment]
Hi,

As a workaround I was able to prevent the **NullReferenceException** to be thrown by updating the **XfxEntry**'s value to **string.Empty** when the **Unfocused** event is triggered:

```xml
<xfx:XfxEntry Placeholder="CPF" Keyboard="Numeric" Unfocused="Cpf_OnUnfocused">
<xfx:XfxEntry.Behaviors>
    <behaviorValidation:MaskedBehavior Mask="XXX.XXX.XXX-XX" />
    <behaviorValidation:CPFValidationBehavior />
</xfx:XfxEntry.Behaviors>
</xfx:XfxEntry>
```

```c#
private void Cpf_OnUnfocused(object sender, FocusEventArgs e)
{
    var entry = (Entry) sender;
    entry.Text = entry.Text ?? string.Empty;
}
```

**Comment by TBertuzzi** [comment]
Hi @guiportooo, 
first thanks for awesome plugin :D .
 Thank you for reporting the error. I will fix it as soon as possible and update the package.
