### ISSUE TITLE
Cor ao sair do campo

### ISSUE THREAD

**Issue by vikazuo** [TBertuzzi/Xamarin.Forms.BehaviorValidationPack#2]
A cor de fundo da tela é preta, com isso o TextColor de todos os campos são brancos...
Porém, nesse quando saio do campo, ele volta a ficar na cor padrão do xamarin...
Como faço para alterar a cor?

**Comment by jadson-medeiros** [comment]
Conseguiu resolver esse?

**Comment by vikazuo** [comment]
nops....

**Comment by TBertuzzi** [comment]
Por padrão ele coloca a Color.Default no lugar de vermelho. A próxima versão vai manter a cor definida do controle.

**Comment by TBertuzzi** [comment]
Implementado na versão 1.1.0.0
