### ISSUE TITLE
Masked not working properly

### ISSUE THREAD

**Issue by SagarPanwala** [TBertuzzi/Xamarin.Forms.BehaviorValidationPack#3]
For Masking, if we apply it on Entry.
- From code behind or Xaml, if we assign text directly like 23032019.
Masking not working working. I know this is not valid case for date time. But if we apply masking for Label and Phone number this is valid scenario. Because is some case we get phone number from api and we need to show in Entry or Label as masked.

**Comment by TBertuzzi** [comment]
Could you attach an example?
