### ISSUE TITLE
Bindable not an instance of AssociatedType

### ISSUE THREAD

**Issue by carlosfsbrasil** [TBertuzzi/Xamarin.Forms.BehaviorValidationPack#4]
Ao executar o próprio projeto de exemplos, ao carregar a tela BehaviorsPackSample a mensagem de erro é exibida: "Bindable not an instance of AssociatedType".

**Comment by ccleverton** [comment]
Acontece o mesmo problema comigo.

**Comment by john-dalsgaard** [comment]
I see the same problem - for both iOS and Android :-(

**Comment by TBertuzzi** [comment]
Estou trabalhando na próxima versão do controle, vou verificar este bug e atualizar o sample também.

**Comment by TBertuzzi** [comment]
Corrigido na versão 1.1.0.0
